data_path: "datasets/diatoms_conc.csv"
wandb_mode: "disabled"
dependent: "diatomBiovol"
predictor: ["temp"]
train_size: 0.5
res_path: "results/"
take_log: false
take_exp: false
predictor: ["temp"]
temp: false